### ISSUE TITLE
Some icons error

### ISSUE THREAD

**Issue by rpaggi** [fabianalexisinostroza/Antu-icons#7]
Hello,

First of all, I loved the Antu icon set, is amazing! Congratulations!

So, I'm having a problem with this icon set, my wifi, bluetooth, sound and some tray icons does not change when I apply the icon set (as you can see at the image bellow).
[https://i.imgur.com/ERAIhtz.png ](url)
I'm using Xubuntu 18.04.

If someone can help me I'll be grateful.

Thanks

**Comment by fabianalexisinostroza** [comment]
Hi ! thanks for comment ... the problems with the icons is because the Antü theme doesn't have all the actions icons (the monochrome), I recommend you change the inherits to a theme compatible. Antü uses Breeze as fallback theme.

For the next update I will add a better support for GTK Desktops, Antü is more KDE friendly now ;)
